<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function countProjects()
    {
       $query = $this->getEntityManager()->getRepository('AppBundle:Project')->findAll();

       $allProjects = count($query);

       return $allProjects;
    }
}
