<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countUsers()
    {
       $query = $this->getEntityManager()->getRepository('AppBundle:User')->findAll();

       $allUsers = count($query);

       return $allUsers;
    }
}
